apiVersion: v1
kind: Service
metadata:
  name: reservation-svc
  labels:
    app: itemreservation-msa
spec:
  #type: NodePort --removed for GCP and Added 'type: LoadBalancer'
  type: LoadBalancer
  ports:
  - port: 8093
    targetPort: 8093
    protocol: TCP
    #nodePort: 31093 -- removed for GCP and Added protocol:TCP
  selector:
    app: itemreservation-msa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation-svc
spec:
  selector:
    matchLabels:
      app: itemreservation-msa
  replicas: 1
  template:
    metadata:
      labels:
        app: itemreservation-msa
    spec:
      containers:
      - name: reservation
        image: docker.io/debanjande/ora-reservation-v1
        ports:
        - containerPort: 8093
