apiVersion: v1
kind: Service
metadata:
  name: onhandquery
  labels:
    app: onhandquery-msa
spec:
  #type: NodePort --removed for GCP and Added 'type: LoadBalancer'
  type: LoadBalancer
  ports:
  - port: 8092
    targetPort: 8092
    protocol: TCP
    #nodePort: 31092 -- removed for GCP and Added protocol:TCP
  selector:
    app: onhandquery-msa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: onhandquery
spec:
  selector:
    matchLabels:
      app: onhandquery-msa
  replicas: 1
  template:
    metadata:
      labels:
        app: onhandquery-msa
    spec:
      containers:
      - name: onhandquery
        image: docker.io/debanjande/ora-onhandquery-v1
        ports:
        - containerPort: 8092
